### ISSUE TITLE
Make it work offline

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/repeat-todo#1]
I'm struggling to make this work. If anyone could help, that'd be sweet.

To get it going, you can run `npm run start` which will start [`quik`](http://npm.im/quik). quik does some fancy things. If you want to try it without anything special, run `npm run predeploy` to build all the files and stuff, then run `npm run serve:dist` to serve the site on port 8080. You'll notice that pretty much the whole app is inlined in `index.html`. Only extras are the favicon and the `service-worker.js` script.

The file responsible for starting the service worker is [`start-service-worker.js`](https://github.com/kentcdodds/repeat-todo/blob/020d9a263b2dc4670b074003fc0bc9d7d4bb4236/src/start-service-worker.js). Then the actual service-worker code is [`service-worker.js`](https://github.com/kentcdodds/repeat-todo/blob/020d9a263b2dc4670b074003fc0bc9d7d4bb4236/service-worker.js). It has the cache polyfill included.

I'm a total newb at this. Thanks for any help!

**Comment by mxstbr** [comment]
Works for me on surge, I'm not sure what the problem here is!

**Comment by kentcdodds** [comment]
Oh really!? Neat!

**Comment by kentcdodds** [comment]
Totally! Works for me, except when I try to simulate offline in Google Chrome DevTools... Any idea why?

**Comment by jakearchibald** [comment]
I think "offline" in devtools makes the tab offline, but not other threads like workers :/

**Comment by kentcdodds** [comment]
Ah! That's a big gotcha! So how do you test it? (And still be able to use Google and stuff :wink:)

**Comment by jakearchibald** [comment]
You can open the devtools for the service worker and change the network there too. Or disconnect your machine from the network :D

**Comment by kentcdodds** [comment]
For anyone seeing this later, to open Service Worker devtools, go to [chrome://inspect/#service-workers](chrome://inspect/#service-workers) and find your tab and click "inspect" then go to the Network tab and use [network throttling](https://developers.google.com/web/tools/chrome-devtools/profile/network-performance/network-conditions?hl=en) to simulate being offline.
:+1: thanks @jakearchibald!

**Comment by jakearchibald** [comment]
You can also get to this from devtools, see the "service workers" section in the "resources" tab.
