### ISSUE TITLE
Figure out how to update mobile devices...

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/repeat-todo#11]
My phone still hasn't updated to have the animations... I'm not sure how to force it to update. I think it's a problem with the service workers or something :-(

**Comment by andrey-skl** [comment]
It's all about cache management. I guess something like `<META HTTP-EQUIV="CACHE-CONTROL" CONTENT="NO-CACHE">` could help

**Comment by kentcdodds** [comment]
I'm not very familiar with that, would that still work with service workers offline?

**Comment by andrey-skl** [comment]
@kentcdodds oh I'm not sure. We should try : )

**Comment by andrey-skl** [comment]
I believe service worker should not be affected by cache control headers

**Comment by kentcdodds** [comment]
I'm wondering if maybe we should try using [upup](https://www.talater.com/upup/) by @TalAter. Would that cover this case for us?

**Comment by BarryThePenguin** [comment]
From [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API)

> The service worker is immediately downloaded when a user first accesses a server worker–controlled site/page.
> 
> After that it is downloaded every 24 hours or so. It _may_ be downloaded more frequently, but it must be downloaded every 24h to prevent bad scripts from being annoying for too long.

There's also mention of updating service workers with [versions](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers#Updating_your_service_worker)

**Comment by kentcdodds** [comment]
Thanks for that @BarryThePenguin!

Can anyone explain to me what this means?

> If your service worker has previously been installed, but then a new version of the worker is available on refresh or page load, the new version is installed in the background, but not yet activated. It is only activated when there are no longer any pages loaded that are still using the old service worker. As soon as there are no more such pages still loaded, the new service worker activates.

I'm not sure I understand what that means in this context.

**Comment by kentcdodds** [comment]
Ah, I think I understand. It's talking about the cache name... So I think that if I update the cache name, it should update eventually (soonish) right?

**Comment by BarryThePenguin** [comment]
Sounds like it, yes

**Comment by kentcdodds** [comment]
Sweet, making a PR now.

**Comment by ta2edchimp** [comment]
I had another idea and fiddled around with it a little bit; I hope it's not too misplaced to elaborate it here in this thread.

When reading Jake Archibald's Offline Cookbook, I stumbled upon the [`stale-while-revalidate`](https://jakearchibald.com/2014/offline-cookbook/#stale-while-revalidate) section.  
Basically, it makes the Service Worker to return a match from the cache (as the [master branch's source currently does](https://github.com/ta2edchimp/repeat-todo/blob/master/service-worker.js#L26-L44)), but also initiates fetching an update and on success, updating the cache to return the updated data on a subsequent request. An implementation in repeat-todo [could look like this](https://github.com/ta2edchimp/repeat-todo/commit/bcd56646edfbb56710e040c962f8d8c3bc706213).

An alternative approach could try to fetch the desired resource (receiving any updates immediately and updating the cached response on success) and only return a match from the cache if there's currently no network connection available (thus, rejecting the fetch promise). [This would be a quick implementation](https://github.com/ta2edchimp/repeat-todo/commit/d85adaeaa20e93e464fee394996348fb9aeb7f06) of such a behaviour.

The latter would be against a real approach of "Offline First", but assures that updated resources would be used as soon as possible, while giving the known positive effects when being offline (that is, if I did not miss anything here — still trying to get my head around Service Workers ...).  
Another (in my eyes) positive side effect would be, that deleting all old keys within the cache would not be necessary, as it is in the `version` approach.

**Comment by kentcdodds** [comment]
Sounds interesting! Thanks for working on it! I'll pull your changes down and try it out later. Mind making a Pull Request?

**Comment by ta2edchimp** [comment]
Sure, would be a pleasure! For which one? The `stale-while-revalidate` way or the one that tries to fetch updated resources prior to returning a cached result?  
Btw: the latter one seems to be similar to the approach [`UpUp`](https://github.com/TalAter/UpUp/blob/master/src/upup.sw.js#L22-L42) uses.

Either way, I will have another look into both quick fiddles I did, clean them up a bit (did not consider the Cache polyfill does not implement a `put` method in one of the examples) and prepare them as PRs later today.

**Comment by kentcdodds** [comment]
Actually, I'm thinking I'd almost rather just use `UpUp`... Nice to not have to solve the problem ourselves. We could just install it from npm and then as part of the `copy` script, copy the necessary files from `node_modules` or something...

**Comment by ta2edchimp** [comment]
Well, in case you want to give it a try, I cleaned everything up and made a Pull Request for the second approach (try fetching from network + update cache / return cached response on network unavailability)
:)

**Comment by kentcdodds** [comment]
Thanks @ta2edchimp! I checked on my phone and it's working now! This is great :+1: You're now on the list of contributors and I'll add you as a committer :dancer:
