### ISSUE TITLE
Optimization: Sourcemap in a separate file

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/repeat-todo#15]
Right now it's inlined on the `index.html` which makes it HUGE! Any thoughts here @satya164? I imagine I need to do things a bit differently...

**Comment by satya164** [comment]
Gimme a day or two. I'll separate it out

**Comment by satya164** [comment]
What do you think the name of the sourcemap file(s) can be? Intially I thought I'll just name it after the HTML bundle, but since there can be multiple sourcemaps possible, wondering what to name them.

**Comment by kentcdodds** [comment]
Hmmm... You could just do the name of the bundle with an index or something.

**Comment by satya164** [comment]
@kentcdodds Yeah, will try that. Thanks :)
