### ISSUE TITLE
Add login and data persistence.

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/repeat-todo#17]
Using `localStorage` is great, but it'd be really nice to be able to login using twitter/facebook/google/email and persisting things in a backend somewhere (firebase?) would be really handy. That way you could do data entry on the computer and use the list on your phone.

Anyone wanna work on this?

**Comment by alayek** [comment]
Sure! Will work on this.

We can use Firebase I suppose, which takes away the pain of having to deploy a back-end on heroku or digital ocean or aws.

**Comment by kentcdodds** [comment]
Cool! Feel free to use your own firebase to develop it, and when it's ready, I'll give you my firebase URL to switch it with. Thanks!
