### ISSUE TITLE
Nothing happens when I press "Complete"

### ISSUE THREAD

**Issue by andrey-skl** [kentcdodds/repeat-todo#2]
1. Go to repeat-todo.surge.sh
2. Create an todo
3. Press complete

Nothing happens. While 'Delete" works as expected

**Comment by kentcdodds** [comment]
Try adding more than one... Note the `repeat` in the name :-)

**Comment by andrey-skl** [comment]
@kentcdodds Oh.. got that. Sorry : D
Some animation could help here to demonstrate the mechanism. Thank you

**Comment by kentcdodds** [comment]
Would you be willing to [makeapullrequest.com](http://makeapullrequest.com) to add a note in the README and/or a demo and/or add animation? :+1:

**Comment by andrey-skl** [comment]
Yeah why not!

**Comment by andrey-skl** [comment]
@kentcdodds proper animation could be tricky with this stateless design. Don't you have any suggestions for https://github.com/huston007/repeat-todo/commit/7979e72451bd90c28442cf647a086137a89f0be8?

Here is some issues:
1. I have to use absolute positions to allow react-motion to move items according to it's positions
2. I have to know items height

**Comment by kentcdodds** [comment]
I love everything except the fact that it's not in the right place ;-)

![animation](https://cloud.githubusercontent.com/assets/1500684/13408782/d2f299e8-deec-11e5-8289-0dd021fce005.gif)

It looks like you made another commit that may have fixed that... Though this is what I'm seeing now... :-(

![after-no-animation](https://cloud.githubusercontent.com/assets/1500684/13408825/0b8983f2-deed-11e5-8f18-f3547fdcb71d.gif)

But I'm sure you'll get it worked out. As far as the animation, I love it. Super cool! Looking forward to the PR!

**Comment by andrey-skl** [comment]
@kentcdodds there is some issue with this build system - it caches index html with styles hardly. Try some refreshes, cmd+refresh and etc)
Also, please pull one more commit.

**Comment by kentcdodds** [comment]
Oh, that's right, yeah, it caches `index.html`. Kinda annoying...

**Comment by kentcdodds** [comment]
Fantastic!

Let's PR this :-) Thanks!

![perfect](https://cloud.githubusercontent.com/assets/1500684/13409013/fa94b660-deed-11e5-9e93-73215e64f220.gif)

**Comment by kentcdodds** [comment]
Also, if you're interested, could you add a `Contributors` section to the `README.md` following the https://github.com/kentcdodds/all-contributors spec?

If you've got time. Thanks!
