### ISSUE TITLE
List breaks if enter todo items with same content.

### ISSUE THREAD

**Issue by andrey-skl** [kentcdodds/repeat-todo#7]
We cant use index of items as key because this is not item UID here. Also we can't use todo text as key because it is not unique. Shouldn't we implement some ID, hash, timestamp or something like this?

**Comment by kentcdodds** [comment]
Yes we should!

I've been thinking about this and I regret not doing this from the start. Whatever we do, we'll need to have a migration strategy (my wife's already spent time entering in a bunch of todos). Ideas?

**Comment by andrey-skl** [comment]
@kentcdodds so we could implement migration handler for store reading or smth like that. I'll think about it

**Comment by kentcdodds** [comment]
:+1:
